# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: worker_messages_service.proto for package ''

require 'grpc'
require_relative './worker_messages_service_pb'

module WorkerMessages
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'WorkerMessages'

    rpc :RecentReports, WorkerReportsRequest, WorkerReports
  end

  Stub = Service.rpc_stub_class
end
