# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker_messages_service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "WorkerReportsRequest" do
    optional :count, :int32, 1
  end
  add_message "WorkerReports" do
    repeated :reports, :message, 1, "WorkerReport"
  end
  add_message "WorkerReport" do
    optional :message, :string, 1
  end
end

WorkerReportsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("WorkerReportsRequest").msgclass
WorkerReports = Google::Protobuf::DescriptorPool.generated_pool.lookup("WorkerReports").msgclass
WorkerReport = Google::Protobuf::DescriptorPool.generated_pool.lookup("WorkerReport").msgclass
