version: "3.7"
services:
  backend:
    image: graphql-example.backend
    build:
      context: ./
      dockerfile: ./dockerfiles/backend/Dockerfile
    volumes:
      - ./:/app
    environment:
      MYSQL_DATABASE: mysql2://root:insecurepassword@database/graphql_development
    links:
      - database
    depends_on:
      - database
  frontend:
    image: graphql-example.frontend
    build:
      context: ./
      dockerfile: ./dockerfiles/frontend/Dockerfile
    volumes:
      - ./:/app
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: insecurepassword
      MYSQL_DATABASE: graphql_development
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    image: nginx
    ports:
      - "80:80"
    links:
      - backend
      - frontend
    depends_on:
      - backend
      - frontend
    volumes:
      - ./config/nginx/application.conf:/etc/nginx/conf.d/default.conf
  graphiql:
    image: npalm/graphiql
    environment:
      API_URL: http://localhost/api/graph
    ports:
      - "4000:4000"
  redis:
    image: redis
  worker:
    image: graphql-example.backend
    restart: on-failure
    
    command: bundle exec ruby bin/hard_worker_daemon.rb run
    volumes:
      - ./:/app

volumes:
  mysql_data:
    driver: local
